#!/usr/bin/env node
// generate_verifier.js — converts snarkjs's verification_key.json into the
// Rust byte-array constants expected by
// contracts/groth16_verifier/src/lib.rs (same VK_ALPHA/VK_BETA/VK_GAMMA/
// VK_DELTA/VK_IC shape as your original groth16-verifier crate).
//
// Usage: node generate_verifier.js ../build/verification_key.json
//
// Output is printed to stdout — paste the DEFAULT_VK_* block directly
// into kyc_registry's lib.rs (or groth16_verifier's lib.rs if you keep
// them as separate contracts/crates).
//
// NOTE: snarkjs exports G1/G2 points as decimal-string coordinate
// arrays, not the compressed/uncompressed byte format Soroban's BN254
// host functions expect. This script does the affine-point ->
// uncompressed-bytes conversion using the same encoding your original
// verifier.rs used (Bn254G1Affine::from_array / Bn254G2Affine::from_array),
// via the ffjavascript library snarkjs already depends on.

const fs = require("fs");
const { buildBn128 } = require("ffjavascript");

function toHexArray(buf) {
  const bytes = Array.from(buf).map((b) => "0x" + b.toString(16).padStart(2, "0"));
  return `[${bytes.join(", ")}]`;
}

async function main() {
  const vkPath = process.argv[2];
  if (!vkPath) {
    console.error("Usage: node generate_verifier.js <verification_key.json>");
    process.exit(1);
  }

  const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));
  const bn128 = await buildBn128();
  const { G1, G2, Fr } = bn128;

  // G1 points come in as [x, y, "1"] decimal strings (projective, z=1 affine)
  const g1ToBytes = (pt) => {
    const x = Fr.e ? undefined : undefined; // unused, kept for clarity
    const affine = G1.fromObject([BigInt(pt[0]), BigInt(pt[1])]);
    return G1.toUncompressed(affine);
  };

  // G2 points come in as [[x_c0,x_c1],[y_c0,y_c1],["1","0"]]
  const g2ToBytes = (pt) => {
    const affine = G2.fromObject([
      [BigInt(pt[0][0]), BigInt(pt[0][1])],
      [BigInt(pt[1][0]), BigInt(pt[1][1])],
    ]);
    return G2.toUncompressed(affine);
  };

  const alpha = g1ToBytes(vk.vk_alpha_1);
  const beta = g2ToBytes(vk.vk_beta_2);
  const gamma = g2ToBytes(vk.vk_gamma_2);
  const delta = g2ToBytes(vk.vk_delta_2);
  const ic = vk.IC.map(g1ToBytes);

  console.log("// AUTO-GENERATED by circuits/scripts/generate_verifier.js — DO NOT EDIT BY HAND");
  console.log(`const DEFAULT_VK_ALPHA: [u8; BN254_G1_SERIALIZED_SIZE] = ${toHexArray(alpha)};`);
  console.log(`const DEFAULT_VK_BETA: [u8; BN254_G2_SERIALIZED_SIZE] = ${toHexArray(beta)};`);
  console.log(`const DEFAULT_VK_GAMMA: [u8; BN254_G2_SERIALIZED_SIZE] = ${toHexArray(gamma)};`);
  console.log(`const DEFAULT_VK_DELTA: [u8; BN254_G2_SERIALIZED_SIZE] = ${toHexArray(delta)};`);
  console.log("");
  console.log(`const DEFAULT_VK_IC: [[u8; BN254_G1_SERIALIZED_SIZE]; ${ic.length}] = [`);
  for (const point of ic) {
    console.log(`    ${toHexArray(point)},`);
  }
  console.log("];");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
